name: Run Python Script Daily

on:
  schedule:
    # Runs every day at 9 AM UTC
    - cron: "0 9 * * *"
  workflow_dispatch:  # allows manual run

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Step 4: Run your script
      - name: Run script
        run: python fetch_fpl.py
